version: '3'
volumes:
  dynamodata:

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -port 3010 -dbPath /home/data/
    ports:
      - '3010:3010'
    # working_dir: /home/dynamodblocal
    user: root
    volumes:
      - dynamodata:/home/data